# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='blog.Image'),
        ),
    ]
