# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160510_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='row',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
