# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20160511_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='New_User',
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.Image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='users',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
    ]
