# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160519_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
