# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_image_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='blog.Image'),
        ),
    ]
