# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160520_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='users',
        ),
        migrations.AddField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(related_name='tagged_users', to='blog.UserProfile'),
        ),
    ]
