# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160620_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(null=True, related_name='tagged_users', to='blog.UserProfile'),
        ),
    ]
