# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friends',
        ),
    ]
