# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_friends_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(related_name='friends_list', to='blog.UserProfile'),
        ),
    ]
