# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
