# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160620_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
