# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160621_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='friends_requests', to='blog.UserProfile'),
        ),
    ]
