# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_friends_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='requests',
        ),
        migrations.AddField(
            model_name='friends',
            name='request_sent',
            field=models.ManyToManyField(blank=True, related_name='friends_requests_sent', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='requests_received',
            field=models.ManyToManyField(blank=True, related_name='friends_requests_received', to='blog.UserProfile'),
        ),
    ]
