# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160621_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='request_sent',
            new_name='requests_sent',
        ),
    ]
