# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_message_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='owner',
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_owner', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='blog.UserProfile'),
        ),
    ]
